# Generated by Django 3.1.1 on 2020-09-24 07:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReceiptInvoice",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("message_sent", models.BooleanField(help_text="If True, invoice message has been sent.", null=True)),
                (
                    "client_name",
                    models.CharField(help_text="Client for which the invoice has been generated", max_length=200),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=32,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 16 digits allowed.",
                                regex="^\\+?1?\\d{9,16}$",
                            )
                        ],
                    ),
                ),
                ("address", models.TextField(blank=True, help_text="Address of the client", null=True)),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, help_text="Name of the bank given by the client", max_length=100, null=True
                    ),
                ),
                (
                    "branch",
                    models.CharField(
                        blank=True, help_text="Branch name for the bank given by the client", max_length=100, null=True
                    ),
                ),
                (
                    "mode_of_payment",
                    models.CharField(
                        choices=[("cash", "Cash"), ("cheque", "Cheque")],
                        default="cash",
                        help_text="Mode of payment which client chose to do the payment.",
                        max_length=10,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Employee who cut the receipt",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PaperForAdvertisement",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the paper in which Advertisement has to be shown", max_length=100
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        help_text="Name of the paper in which Advertisement has to be shown", max_length=100
                    ),
                ),
                (
                    "edition",
                    models.CharField(
                        help_text="List of editions in which Advertisement has to be shown", max_length=100
                    ),
                ),
                ("rate", models.IntegerField(help_text="Rate at which the amount has to be charged")),
                (
                    "extra_lines_or_words",
                    models.IntegerField(blank=True, help_text="Number of extra lines in this paper.", null=True),
                ),
                (
                    "cost_of_one_extra_line_or_word",
                    models.IntegerField(
                        blank=True, help_text="Cost of one extra line or word excluding GST.", null=True
                    ),
                ),
                (
                    "amount_charged",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Amount(in digits) charged to the client for this paper.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "amount_charged_in_words",
                    models.CharField(
                        blank=True,
                        help_text="Amount(in words) charged to the client for this paper.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "receipt_invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="total_papers",
                        to="receipt_invoice.receiptinvoice",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DatesForPaperAdvertisement",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                (
                    "paper_for_advertisement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="all_dates",
                        to="receipt_invoice.paperforadvertisement",
                    ),
                ),
            ],
        ),
    ]
