# Generated by Django 3.1.1 on 2020-10-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipt_invoice", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="receiptinvoice",
            name="message_response",
            field=models.CharField(
                help_text="Response sent by fast2sms api about message sent status", max_length=500, null=True
            ),
        ),
    ]
