# Generated by Django 3.1.1 on 2020-10-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptinvoice',
            name='message_response',
            field=models.JSONField(null=True),
        ),
    ]
