# Generated by Django 3.1.1 on 2020-10-04 08:40

from django.db import migrations
from django.db.models import Q


def backfill_receipt_caption(apps, schema_editor):
    ReceiptInvoice = apps.get_model("receipt_invoice", "ReceiptInvoice")

    for receipt_invoice in ReceiptInvoice.objects.all():
        try:
            receipt_invoice.caption = receipt_invoice.total_papers.filter(~Q(caption__icontains="same"))[0].caption
        except IndexError:
            receipt_invoice.caption = "Caption"

        receipt_invoice.save()


def blank_migration(*args, **kwargs):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("receipt_invoice", "0003_receiptinvoice_caption"),
    ]

    operations = [migrations.RunPython(backfill_receipt_caption, blank_migration)]
