# Generated by Django 3.1.1 on 2020-10-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipt_invoice", "0004_backfill_caption"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paperforadvertisement",
            name="caption",
        ),
        migrations.AlterField(
            model_name="receiptinvoice",
            name="caption",
            field=models.CharField(help_text="Caption for the receipt.", max_length=100),
        ),
    ]
